"""empty message

Revision ID: 6356a86fd258
Revises: 
Create Date: 2019-04-16 19:07:38.518363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6356a86fd258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('current_moving_session', sa.Integer(), nullable=True),
    sa.Column('a0', sa.Integer(), nullable=True),
    sa.Column('a1', sa.Integer(), nullable=True),
    sa.Column('a2', sa.Integer(), nullable=True),
    sa.Column('b0', sa.Integer(), nullable=True),
    sa.Column('b1', sa.Integer(), nullable=True),
    sa.Column('b2', sa.Integer(), nullable=True),
    sa.Column('c0', sa.Integer(), nullable=True),
    sa.Column('c1', sa.Integer(), nullable=True),
    sa.Column('c2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('games_win_count', sa.Integer(), nullable=True),
    sa.Column('games_lost_count', sa.Integer(), nullable=True),
    sa.Column('administrator', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_games_lost_count'), 'user', ['games_lost_count'], unique=False)
    op.create_index(op.f('ix_user_games_win_count'), 'user', ['games_win_count'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('game_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_code', sa.Integer(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_game_joinable', sa.Boolean(), nullable=True),
    sa.Column('game_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_data_id'], ['game_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_room_game_code'), 'game_room', ['game_code'], unique=True)
    op.create_index(op.f('ix_game_room_start_timestamp'), 'game_room', ['start_timestamp'], unique=False)
    op.create_table('game_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_message_timestamp', sa.DateTime(), nullable=True),
    sa.Column('current_ongoing_game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_ongoing_game_id'], ['game_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_game_session_last_message_timestamp'), 'game_session', ['last_message_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_session_last_message_timestamp'), table_name='game_session')
    op.drop_table('game_session')
    op.drop_index(op.f('ix_game_room_start_timestamp'), table_name='game_room')
    op.drop_index(op.f('ix_game_room_game_code'), table_name='game_room')
    op.drop_table('game_room')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_games_win_count'), table_name='user')
    op.drop_index(op.f('ix_user_games_lost_count'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('game_data')
    # ### end Alembic commands ###
